### ISSUE TITLE
Is supported, check the rc1.4beta branch please

### ISSUE THREAD

**Issue by ghost** [mike-kfed/roundcube-thunderbird_labels#50] opened 2019-09-01 19:40 UTC
Is supported, check the rc1.4beta branch please

_Originally posted by @mike-kfed in https://github.com/mike-kfed/roundcube-thunderbird_labels/issues/39#issuecomment-435059587_

No.It isn't

**Comment by mike-kfed** [comment] 2019-09-02 08:44
Can you please explain in detail what "isn't"?

**Comment by varshitgithub** [comment] 2019-09-03 17:03
This plugin isn't supported in latest elastic theme.Only panel and options appear in settings

**Comment by mike-kfed** [comment] 2019-09-03 18:32
I have no idea what your sentence means. Using Roundcube v1.4rc1 and my rc1.4beta branch shows the interface and settings in the Elastic style, therefore it is fully working. What versions of the two softwares do you use? Are there any error messages in the browser console? Please be specific about what you have, try to do and what doesn't work.

**Comment by RolandSM** [comment] 2019-10-24 06:56
Hello,
I try it on 1.4-rc2 and see only a outgreyed icon with no function.
I get a error like:
`TypeError: rcm_tb_label_find_main_window(...) is null`

**Comment by RolandSM** [comment] 2019-10-24 07:05
I tried it with Larry Skin and it works. Only on Elastic it shows that error.

**Comment by mike-kfed** [comment] 2019-10-24 07:43
what's the full traceback of that error please? Also what are you doing to trigger it? For me in Elastic 3 column layout tb-labels works fine.

**Comment by mike-kfed** [comment] 2019-10-24 07:57
I assume it's happening in popup windows? please try with the fix I pushed

**Comment by mike-kfed** [comment] 2019-10-24 10:04
in what view is that happening? neither in the 3 column main screen nor in "open in new window" this happens to me. screenshot from my new window view attached
![image](https://user-images.githubusercontent.com/5859617/67475361-55e1ea00-f656-11e9-8bf8-7362e9decc42.png)

**Comment by RolandSM** [comment] 2019-10-24 10:07
On both views. I use the latest release from roundcube...
![Screenshot_20191024_120628](https://user-images.githubusercontent.com/16316603/67475592-c7ba3380-f656-11e9-8458-01baca2ac491.png)

**Comment by mike-kfed** [comment] 2019-10-24 10:19
I too use roundcube 1.4-rc2. No idea what causes this, is there no log message in the browser console? also nothing in the php log?

**Comment by RolandSM** [comment] 2019-10-25 06:02
Today I run different browser and also changed from PHP 7.0 to 7.3
Same issue.
In error.log now entries are shown...
A click on the icon shows nothing.

Only output is a warning like:
`Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: MYROUNDCUBE/skins/elastic/deps/bootstrap.min.css?s=1550069270
Source-Map-Adresse: bootstrap.min.css.map`

**Comment by RolandSM** [comment] 2019-10-25 06:08
Source-Map Warning is fixed, issue is present...

**Comment by mike-kfed** [comment] 2019-10-25 11:17
the only way I could reproduce your not showing of the icon is by breaking access to `./thunderbird_labels/skins/elastic/tb_label.css` (i.e. server doesn't have access to the file due to ownership or behind symlink). but that also generates an error message in the console, that server returned 403 on those resources.
I just did a vanilla install of roundcube-1.4rc2 from their tar.gz on a apache/php-7.3 and all buttons show up fine. Same is true for my dev server with is based on git clone of roundcube on tag 1.4rc2 running on nginx with php7.3-fpm. both servers are gentoo-linux.
Something breaks your skin styling, it should show a reasoning in browser though. What happens if you inspect the button? The css inspector shows how the style is computed:
![grafik](https://user-images.githubusercontent.com/5859617/67567178-c279e900-f729-11e9-8c76-f10502f63f1b.png)

**Comment by RolandSM** [comment] 2019-10-26 04:57
Looks completely different...
What i´ve done... Installed the Roundcube RC2 with only downloading files, extracting and modifying the config File.
I downloaded your latest release and activate it in config file.
In YOUR skin folder is no elastic subfolder. As in your description I copy from default or larry. But both also with errors in styling (see screenshot with BULLET option enabled) and no functionality. If I have no elastic folder inside your thunderbird labels it looks like my first image.

I can give you access if you want?

![Screenshot_20191026_064905](https://user-images.githubusercontent.com/16316603/67614430-2b5e7100-f7bd-11e9-9ead-e9b223a1f805.png)

**Comment by mike-kfed** [comment] 2019-10-26 05:03
there is no release tgz of my 1.4beta branch, you have to git clone my repo and checkout the branch.

**Comment by RolandSM** [comment] 2019-10-26 05:09
Ouh... It works. I downloaded your 1.3.2 release and merged your last changes manually. With the git clone of your 1.4b branche it works.

Nice nice nice. Thank you very much.

**Closed** 2020-06-15 09:15 UTC
