### ISSUE TITLE
Labels do not preserve their status across users logon/logoff.

### ISSUE THREAD

**Issue by sch779** [mike-kfed/roundcube-thunderbird_labels#54] opened 2020-03-12 11:51 UTC
Labels do not preserve their status across users logon/logoff.

**Comment by mike-kfed** [comment] 2020-03-12 11:55
Sounds like an issue with your imap server and not this plugin.

**Comment by sch779** [comment] 2020-03-13 11:27
Why? Or label status saved via IMAP on server?

**Comment by mike-kfed** [comment] 2020-03-13 11:45
Yes those are imap labels that are shown and modified. Since nobody else has the problem you have, it likely is with your imap server. Also you give no details what exactly the issue is, are there any errors in the browser console for example? Which label exactly isn't preserved? what version do you use of roundcube and what version of this plugin,...

**Comment by sch779** [comment] 2020-03-13 12:10
Is there really way to processing labels in IMAP protocol? Thunderbird definitely does not save labels on IMAP server, but stores them locally.

There are no errors in browser console. No one label preserved, from 1 to 5.

Tested on several vesrions of Roundcube and plugin. For now it's Rounfcube 1.4.3 and plugin 1.4rc2.

**Comment by mike-kfed** [comment] 2020-03-13 12:33
there is a newer version of my plugin v1.4.2 maybe that helps already.

Yes IMAP allows the setting of custom flags, the whole premise of that plugin is based on that. Including thunderbird storing the flags/labels on the server.

**Comment by sch779** [comment] 2020-03-13 12:56
Oh, that's my fault, plugin version 1.4.2 (looked in Changelog for version number).

My desktop Thunderbird client perfectly preserve labels on POP3 account as well on IMAP account. So Thunderbird definetly store it locally.

Server is IMAP4rev1 and supports FLAGS option:
* FLAGS (\Seen \Answered \Flagged \Deleted \Draft \Recent $Forwarded $MDNSent)

**Comment by mike-kfed** [comment] 2020-03-13 13:24
oh, didn't update the changelog, thanks for the info!

sure thunderbird keeps the flags locally for POP3 but there is no way to share them with the server and therefore no way for roundcube to see the existing flags or modify them. Please make sure both thunderbird and roundcube access via IMAP, then the flags can be seen by both clients the same way.

**Comment by sch779** [comment] 2020-03-19 11:17
I was happy to help!

I have double checked that both Thunderbird and Roundcube access same account at same server via IMAP. Labels made on Thunderbird preserved across mail client restart. But these labels does not shown on Roundcube. Also labels made on Roundcube does not preserve across logon/logoff and does not reflect on Thunderbird.

**Comment by mike-kfed** [comment] 2020-04-04 14:26
The only hint I can give you is to inspect the IMAP commands that are exchanged, maybe you can find your problem there. tTis is unlikely an issue with my plugin but with your setup, therefore I will close this report. If you need help debugging your setup we can meet on IRC and discuss there.

**Closed by mike-kfed** 2020-04-04 14:26 UTC
